#!/bin/bash
# dialog-test
# Description: Testing the dialog command
# Tue 06 Aug 2019 11:22:01 AM PDT

MENU_TITLE="${USER}'s cases"
FILE="/home/jcardarelli/case_tracker.yaml"

error() {
  local timeformat='%Y-%m-%dT%H:%M:%S%z'
  echo "[$(date +${timeformat})] [ERROR]: $@" >&2
  exit 1
}

ar=()
num=1
while read n s ; do
  ((num + 1))
  ar+=($num $n "$s")
done < $FILE
dialog  --menu "$MENU_TITLE "  20 50 30 "${ar[@]}"

case $? in
  0)
    echo "output was $?"
    ;;
  1)
    echo "You chose Option 1"
    ;;
  2)
    echo "You chose Option 2"
    ;;
  3)
    echo "You chose Option 3"
    ;;
esac
