#!/bin/bash
# dialog-test2
# Description: Second dialog command test
# Wed 31 Jul 2019 10:13:17 AM PDT

error() {
  local timeformat='%Y-%m-%dT%H:%M:%S%z'
  echo "[$(date +${timeformat})] [ERROR]: $@" >&2
  exit 1
}

HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="Backtitle here"
TITLE="Title here"
MENU="Choose one of the following options:"

OPTIONS=(1 "Option 1"
         2 "Option 2"
         3 "Option 3")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
  1)
    echo "You chose Option 1"
    ;;
  2)
    echo "You chose Option 2"
    ;;
  3)
    echo "You chose Option 3"
    ;;
esac
